apiVersion: v1
kind: Service
metadata:
  name: nlb-usermgmt-restapp-service
  labels:
    app: usermgmt-restapp
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  selector:
    app: usermgmt-restapp
  ports:
  - name: http
    port: 80
    targetPort: 8095
    # nodePort: 30030
  type: LoadBalancer ## Default load balancer to be created is Classic Loadbalancers