apiVersion: v1
kind: Namespace
metadata:
  name: prod1
  namespace: prod1
---

apiVersion: v1
kind: LimitRange
metadata:
  name: ns-resource-limits-range
  namespace: prod1
spec:
  limits:
    - default:
        memory: "400Mi"
        cpu: "500m"
      defaultRequest:
        memory: "200Mi"
        cpu: "250m"
      type: Container