apiVersion: v1
kind: Service
metadata:
  name: my-backend-service
  labels:
    app: backend-app
    tier: backend
spec:
  selector:
    app: backend-app
  ports:
  - name: http
    port: 8080
    targetPort: 8080