apiVersion: v1
kind: Service
metadata:
  name: deployment-svc
  labels:
    app: deploy-svc
spec:
  selector:
    app: pod-deployment
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30003
  type: NodePort