apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  labels:
    tier: frontend
spec:
  selector:
    app: frontend-deploy
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30004
  type: NodePort