apiVersion: v1
kind: Secret
metadata:
  name: mysql-db-credentials
type: Opaque
data:
  db-password: ZGJwYXNzd29yZDExCg==
  db-name: dXNlcm1nbXQK
  db-port: MzMwNgo=
  db-hostname: bXlzcWwK
  db-username: cm9vdAo=
