apiVersion: v1
kind: Pod
metadata:
  labels:
    run: kubenginx
  name: kubenginx
  namespace: default
spec:
  containers:
    name: kubenginx
  - image: stacksimplify/kubenginx:1.0.0
    imagePullPolicy: IfNotPresent
    