apiVersion: v1
kind: Service
metadata:
  namespace: prod1
  name: mysql
spec:
  selector:
    app: mysql
  ports:
  - name: http
    port: 3306
  clusterIP: None # This means we are goint to use Pod IP