apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: prod1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.6
        ports:
        - containerPort: 3306
          name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: dbpassword11
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: usermanagement-dbcreation-script
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: ebs-pvc ## EBS volume claim
      - name: usermanagement-dbcreation-script
        configMap:
          name: usermanagement-dbcreation-script ## run a script defined on configMap to create a new database


