apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: hello
  labels:
    app: hello
spec:
  replicas: 6
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello-world
        image: jmcglobal/nginx:v2 
        imagePullPolicy: IfNotPresent

---
apiVersion: v1
kind: Service
metadata:
  name: rs-svc
spec:
  selector:
    app: hello
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30030
  type: NodePort